'use client';

import { useState } from 'react';
import { Box, Stack, Typography } from '@mui/material';
import * as UI from '../../components/ui';
import type { StatusBadgeStatus } from '../../components/ui/status-badge';

const statuses: StatusBadgeStatus[] = ['available', 'partial', 'proxy', 'candidate', 'unvalidated', 'validated', 'revised', 'rejected', 'superseded', 'awaiting-source', 'contractual', 'in-review', 'ready-to-sign-off', 'signed-off', 'draft', 'active', 'retired', 'not-published', 'computed-fact', 'model-classification'];
const sample = [{ id: 1, name: 'North region', count: 12 }, { id: 2, name: 'West region', count: 8 }, { id: 3, name: 'Central region', count: 19 }];
export default function DesignGallery() {
  const [dialog, setDialog] = useState(false); const [panel, setPanel] = useState(false); const [tab, setTab] = useState('one');
  const [choice, setChoice] = useState(''); const [segment, setSegment] = useState('all'); const [clients, setClients] = useState(['North region']); const [dateRange, setDateRange] = useState({ from: '2026-07-01', to: '2026-09-30' }); const [actionDialog, setActionDialog] = useState(false);
  const activities = Array.from({ length: 7 }, (_, index) => ({ id: index, time: `2026-10-0${Math.max(1, 7 - index)}T12:15:00Z`, actor: index % 2 ? 'Alex Morgan' : 'Local test reviewer', action: index === 0 ? 'Validated a finding' : 'Updated the review', qualifiers: `Example activity ${index + 1}` }));
  return <Box sx={{ display: 'grid', gap: 3, maxWidth: 1100 }}><UI.PageHeader title="Component gallery" description="Development reference for shared report workspace components." actions={<UI.Button disabled>Sign off</UI.Button>} actionHint="Decide every item before signing off." details={[{ label: 'Analysis run ID', value: 'run-12345' }, { label: 'Version', value: 'version-abcde' }]} />
    <section><Typography variant="h2" component="h2" sx={{ mb: 1 }}>Status vocabulary</Typography><Stack direction="row" flexWrap="wrap" gap={1}>{statuses.map((status) => <UI.StatusBadge key={status} status={status} />)}</Stack><Box sx={{ mt: 2, borderLeft: 3, borderColor: 'brand.information', p: 1.5, bgcolor: 'brand.informationLight' }}><UI.StatusBadge status="unvalidated" /><Typography sx={{ mt: 1 }}>Model-drafted content is visibly marked and remains unvalidated.</Typography></Box></section>
    <section><Typography variant="h2" component="h2" sx={{ mb: 1 }}>Data table</Typography><Stack spacing={2}><UI.DataTable rows={sample} columns={[{ id: 'name', label: 'Region', sortable: true, minWidth: 180 }, { id: 'count', label: 'Cases', sortable: true, align: 'right', width: 120 }]} getRowId={(row) => row.id} label="Example regional cases" /><UI.DataTable rows={sample.slice(0, 0)} columns={[{ id: 'name', label: 'Region' }]} getRowId={(row) => row.id} emptyTitle="No regions found" /><UI.DataTable rows={sample} columns={[{ id: 'name', label: 'Region' }]} getRowId={(row) => row.id} loading label="Example loading table" /><UI.DataTable rows={sample} columns={[{ id: 'name', label: 'Region' }]} getRowId={(row) => row.id} error={{ state: 'unavailable' }} onRetry={() => undefined} label="Example unavailable table" /><UI.DataTable rows={sample} columns={[{ id: 'name', label: 'Region' }]} getRowId={(row) => row.id} bordered={false} rowsPerPageOptions={[2, 3]} initialRowsPerPage={2} label="Unbordered paginated table" /></Stack><Stack direction="row" flexWrap="wrap" gap={2} sx={{ mt: 2 }}><UI.StateView state="loading" /><UI.StateView state="empty" /><UI.StateView state="error" onRetry={() => undefined} /><UI.StateView state="unavailable" onRetry={() => undefined} /><UI.StateView state="forbidden" /><UI.StateView state="not_found" /></Stack></section>
    <section><Typography variant="h2" component="h2" sx={{ mb: 1 }}>Fields and notices</Typography><Stack spacing={2} maxWidth={520}><UI.Field label="Report title" required helperText="Use a clear business description." /><UI.Field label="Reviewer note" kind="textarea" rows={3} helperText="Add context for the audit history." /><UI.Field label="Sample count" kind="number" errorText="Enter a whole number greater than zero." /><UI.Field label="Status" kind="select" options={[{ value: 'draft', label: 'Draft' }, { value: 'active', label: 'Active' }]} /><UI.Field label="Client (default option chosen)" kind="select" value="" onChange={() => undefined} options={[{ value: '', label: 'All clients' }, { value: 'north', label: 'North region' }]} helperText="S17: the default option shows its label." /><UI.Notice title="Information" tone="info">This is an informational message.</UI.Notice><UI.Notice title="Warning" tone="warning">Review the requirements before continuing.</UI.Notice><UI.Notice title="Error" tone="error">The request could not be saved.</UI.Notice><UI.Notice title="Success" tone="success">The change was saved.</UI.Notice></Stack></section>
    <section><Typography variant="h2" component="h2" sx={{ mb: 1 }}>Navigation and disclosure</Typography><UI.Breadcrumbs items={[{ label: 'Reports', href: '/dashboard/reports' }, { label: 'Review' }]} /><UI.Tabs value={tab} onChange={setTab} options={[{ value: 'one', label: 'Overview' }, { value: 'two', label: 'Evidence' }, { value: 'three', label: 'History' }]} /><UI.Tabs param="gallery-tab" options={[{ value: 'one', label: 'URL-synced overview' }, { value: 'two', label: 'URL-synced evidence' }]} /><UI.Disclosure title="Show more detail"><Typography>Additional supporting information appears here.</Typography></UI.Disclosure></section>
    <section><Typography variant="h2" component="h2" sx={{ mb: 1 }}>Actions and choices</Typography><Stack spacing={2} maxWidth={700}><Stack direction="row" flexWrap="wrap" gap={1.5}><UI.Button variant="primary">Primary action</UI.Button><UI.Button variant="secondary">Secondary at rest</UI.Button><UI.Button variant="tertiary">Tertiary action</UI.Button><UI.Button variant="destructive">Destructive action</UI.Button><UI.Button disabled>Disabled primary</UI.Button><UI.Button loading>Save review</UI.Button><UI.MoreActionsMenu actions={[{ label: 'Open example dialog', onSelect: () => setActionDialog(true) }, { label: 'Unavailable action', onSelect: () => undefined, disabled: true }]} /></Stack><UI.ChoiceGroup label="Decision with no default" options={[{ value: 'validate', label: 'Validate', helperText: 'The evidence supports this finding.' }, { value: 'revise', label: 'Revise' }, { value: 'reject', label: 'Reject' }]} value={choice} onChange={setChoice} /><UI.ChoiceGroup label="Horizontal short choices" row value="html" options={[{ value: 'html', label: 'HTML' }, { value: 'excel', label: 'Excel' }]} /><UI.ChoiceGroup label="Choice validation" options={[{ value: 'yes', label: 'Yes' }]} errorText="Choose an option to continue." /><UI.FilterBar label="Example filters" active={clients.length > 0} onClear={() => setClients([])}><UI.SegmentedControl label="Status" value="all" onChange={() => undefined} options={[{ value: 'all', label: 'All', count: 3 }, { value: 'review', label: 'In review', count: 2 }, { value: 'signed', label: 'Signed off', count: 0 }]} /><Box sx={{ minWidth: 280 }}><UI.MultiSelect label="Clients" emptyLabel="All clients" inBar options={['West region', 'North region']} value={clients} onChange={setClients} /></Box></UI.FilterBar><UI.SegmentedControl label="Decision status" value={segment} onChange={setSegment} options={[{ value: 'all', label: 'All', count: 16 }, { value: 'undecided', label: 'Undecided', count: 4 }, { value: 'decided', label: 'Decided', count: 12 }]} /></Stack><UI.Dialog open={actionDialog} title="Example action" description="This menu action opened a dialog." onConfirm={() => setActionDialog(false)} onClose={() => setActionDialog(false)} /></section>
    <section><Typography variant="h2" component="h2" sx={{ mb: 1 }}>Activity and progress</Typography><Stack spacing={2} maxWidth={700}><UI.ActivityList entries={activities} /><UI.ActivityList entries={[]} emptyText="No activity to show." /><UI.ProgressSummary decided={4} total={16} label="findings" /><UI.ProgressSummary decided={16} total={16} label="findings" /></Stack></section>
    <section><Typography variant="h2" component="h2" sx={{ mb: 1 }}>Request form components</Typography><Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', md: '1fr 1fr' }, gap: 3 }}><Stack spacing={2}><UI.MultiSelect label="Clients" options={['West region', 'North region', 'Central region']} value={clients} onChange={setClients} recent={['North region']} helperText="Choose one or more clients." required /><UI.MultiSelect label="Clients with validation error" options={['Alpha', 'Beta']} value={[]} onChange={() => undefined} errorText="Choose at least one client." /><UI.DateRangeField value={dateRange} onChange={setDateRange} /><UI.DateRangeField value={{ from: '2026-10-15', to: '2026-10-01' }} onChange={() => undefined} errorText="The selected date range is unavailable." /></Stack><Stack spacing={2}><UI.SummaryPanel rows={[{ label: 'Promptbook', value: 'Operations review · v3' }, { label: 'Clients', value: 'North region' }, { label: 'Period', value: '1 Jul 2026 – 30 Sep 2026' }]} matchCount={24} /><UI.SummaryPanel loading /><UI.SummaryPanel matchCount={0} /><UI.SummaryPanel error="The matching count could not be loaded." /></Stack></Box></section>
    <section><Typography variant="h2" component="h2" sx={{ mb: 1 }}>Overlays</Typography><Stack direction="row" gap={1.5}><UI.Button variant="secondary" onClick={() => setDialog(true)}>Open confirmation dialog</UI.Button><UI.Button variant="secondary" onClick={() => setPanel(true)}>Open side panel</UI.Button></Stack><UI.Dialog open={dialog} title="Confirm this action" description="This demonstrates focus containment and return." onConfirm={() => setDialog(false)} onClose={() => setDialog(false)} /><UI.SidePanel open={panel} title="Citation details" onClose={() => setPanel(false)}><Typography>Source and citation details appear here.</Typography></UI.SidePanel></section>
  </Box>;
}
